PR for revamped settings app:
withfig/config pull request #25
Opened 2021-07-22 23:00 UTC by Nutlope

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature

**What is the new behavior (if this is a feature change)?**
- adding sidebarName prop for new settings side menu
- Rewrote certain names and descriptions

2021-07-24 07:56 UTC, QuiiBz reviewed
Looks like the whole file has two extra spaces at the beginning of each line

2021-07-24 07:56 UTC, QuiiBz commented on tools/all-settings.json
> +      "sidebarHeading": "Psuedoterminal",
```suggestion
      "sidebarHeading": "Pseudoterminal",
```

2021-07-24 07:56 UTC, QuiiBz commented on tools/all-settings.json
> +      "sidebarHeading": "Psuedoterminal"
```suggestion
      "sidebarHeading": "Pseudoterminal"
```

2021-07-29 07:16 UTC, QuiiBz approved these changes

2021-07-30 03:09 UTC, mschrage requested changes
Just had a look at this. I think that `sidebarName` is does not need to exist. We should just put this information in the `title` property. (I like your updates to the copy, just don't think we need a new property.)

I also would make `sidebarHeading` more generic. Perhaps `category` instead?

2021-08-02 21:30 UTC, mschrage approved these changes
🎉

2021-08-02 21:31 UTC, merged