Fix right prompt issues
withfig/config pull request #59
Opened 2021-09-14 03:13 UTC by fwesss

The right prompt missing and af-magic incompatibility were actually 2 separate issues.

## Right prompt missing with Fig installed

The right prompt can be set in zsh by modifying either RPS1 or RPROMPT. These 2 variables do the exact thing but are not linked. If RPS1 is set, RPROMPT could be unset and vice versa. 

In our post.zsh, we copied RPS1 then added it back in. If the user used RPROMPT to set their right prompt, we were ignoring it so it would be missing entirely.

Changed post.zsh to copy whichever variable was set.

## Broker right prompt with af-magic theme

The af-magic right prompt is set:
```bash
RPS1='${return_code}'
(( $+functions[virtualenv_prompt_info] )) && RPS1+='$(virtualenv_prompt_info)'
RPS1+=' $my_gray%n@%m%{$reset_color%}%'
```

The 3rd line escapes the prompt with a final '%'. When we add back in RPS1, we expand it with another '%' which mangles the entire prompt.

Added an explicit check for af-magic so that RPS1 gets set as if it has already been expanded. Otherwise, set as usual.

Re: https://github.com/withfig/fig/issues/403 & https://github.com/withfig/fig/issues/311

2021-09-14 17:40 UTC, sullivan-sean requested changes
Great catch and great changes, would be great to use this approach of checking whether something exists before modifying for all prompts!

2021-09-14 17:40 UTC, sullivan-sean commented on shell/post.zsh
> +  [[ -v RPS1 ]] && FIG_USER_RPS1="$RPS1"
I like this approach of setting the variables only if the variable is already set to avoid changing things too much -- it would actually be great to do this for all of the prompt variables. I also think it might make sense to remove these checks from setting the `FIG_USER_` values, but we should have them before all of the lines that set prompt values, including in the pre-exec hook above.

2021-09-14 17:40 UTC, sullivan-sean commented on shell/post.zsh
> +  # The af-magic theme adds a final # to expand. We need to paste without the #
Should these be `%` instead of `#` in the comment?

2021-09-14 17:40 UTC, sullivan-sean commented on shell/post.zsh
> +    RPS1="%{$START_PROMPT%}$RPS1{$END_PROMPT%}"
We should make this check for the last character in `$RPS1` to check if its a `%` to handle cases besides just `af-magic` and it would be great to encapsulate this logic in a function like `fig_wrap_prompt` or something and do this for all prompts just in case somebody decides to set `PS1="%"`

2021-09-14 17:40 UTC, sullivan-sean commented on shell/post.zsh
>    FIG_USER_PS1="$PS1"
We use the `FIG_USER_` prompt variables to store the value that the user last set the prompt to so that we can restore these values on preexec. This means that when a user runs `echo $PS1` they won't see any of the changes Fig has made to the prompt. 

We should make sure we are restoring `RPROMPT` in the same way so that if `RPROMPT` is set then when the user runs `echo $RPROMPT` they see the prompt they set and not the modified version we create in the precmd hook. i.e. see here:

https://github.com/withfig/config/blob/5a10563df61e89a33147f14d0d2e6bba6c10fb48/shell/post.zsh#L24-L29

2021-09-14 21:16 UTC, fwesss commented on shell/post.zsh
> +  [[ -v RPS1 ]] && FIG_USER_RPS1="$RPS1"
Moved checks before setting prompt values

2021-09-14 21:17 UTC, fwesss commented on shell/post.zsh
> +  # The af-magic theme adds a final # to expand. We need to paste without the #
Oops! Generalized function so those comments no longer apply.

2021-09-15 00:01 UTC, fwesss commented
Dangling '%' appears to be a bug specific to af-magic. Going to leave in check for af-magic and apply a fix in that one case. I'll submit a PR to oh-my-zsh to fix on their end so we can remove patch in the future.

Additionally added logic to check if prompt variables are set before copying and resetting them. There are synonymous names for each prompt but they are not always linked.

Example:
PROMPT, prompt, and PS1 all refer to the same thing. If one of those names is set, the others may remain unset depending on the prompt.
However, if two or more synonymous variables are set, the variable set last will take precedence.

PROMPT, prompt, and PS1 are linked
```bash
$ prompt="%t"
> 4:52PM
$ PS1="%n"
> wesfeller
$ echo $prompt
> %n
$ echo $PS1
> %n
$ echo $PROMPT
> %n
```

RPS1 and RPROMPT are unlinked
```bash
$ RPS1="%t"
> 4:52PM
$ echo $RPS1
> %t
$ echo $RPROMPT
>
```

2021-09-15 00:23 UTC, sullivan-sean approved these changes
This looks perfect, and thanks for the super comprehensive write-up describing all this :)

2021-09-15 00:23 UTC, sullivan-sean commented on shell/post.zsh
> +    if [[ -d /Applications/Fig.app || -d ~/Applications/Fig.app ]] && command -v fig 2>&1 1>/dev/null; then
nit: was this intentional?

2021-09-15 00:23 UTC, sullivan-sean commented on shell/post.zsh
> +fig_wrap_prompt() {
can get rid of this now

2021-09-15 21:56 UTC, fwesss commented on shell/post.zsh
> +    if [[ -d /Applications/Fig.app || -d ~/Applications/Fig.app ]] && command -v fig 2>&1 1>/dev/null; then
No, I'm not sure how that happened. Fixed!

2021-09-16 00:38 UTC, merged